In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import sys

sys.path.append('../src/')

import load_data


from load_data import load_instacart_data

In [3]:
data = load_instacart_data()

orders = data['orders']
order_products_prior = data['order_products_prior']
products = data['products']

In [5]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [4]:
# merge of the 2 tables to get the product names
orders_products=order_products_prior.merge(products[['product_id', 'product_name']], on='product_id', how='left')

In [5]:
# how many times each product was ordered
product_counts = orders_products['product_id'].value_counts()

# filter on top 1000 products
top_n=200
top_products = product_counts.head(top_n).index

filtered_orders_products = orders_products[orders_products['product_id'].isin(top_products)]

filtered_orders_products.head()

,order_id,product_id,add_to_cart_order,reordered,product_name
0,2,33120,1,1,Organic Egg Whites
1,2,28985,2,1,Michigan Organic Kale
5,2,17794,6,1,Carrots
9,3,33754,1,1,Total 2% with Strawberry Lowfat Greek Strained...
10,3,24838,2,1,Unsweetened Almondmilk

In [9]:
# percentage of transactions kept in scope after filtering on top_n products
percentage_transactions=len(filtered_orders_products)/len(order_products_prior)
print(percentage_transactions)

0.5400123615328116

In [6]:
# filter basket sizes to remove outliers
order_sizes=filtered_orders_products.groupby('order_id').size()

valid_orders=order_sizes[(order_sizes>3) & (order_sizes<20)].index
filtered_orders=filtered_orders_products[filtered_orders_products['order_id'].isin(valid_orders)]

In [8]:
len(filtered_orders)

14001681

In [7]:
basket_list=filtered_orders.groupby('order_id')['product_name'].apply(list).reset_index()
basket_list.columns=['order_id', 'products']

In [10]:
basket_list.head()

   order_id                                           products
0         2  [Organic Egg Whites, Michigan Organic Kale, Ga...
1         3  [Total 2% with Strawberry Lowfat Greek Straine...
2         4  [Plain Pre-Sliced Bagels, Goldfish Cheddar Bak...
3         5  [Bag of Organic Bananas, Organic Raspberries, ...
4         9  [Organic Red Radish, Bunch, Whole White Mushro...

In [15]:
len(basket_list)

1762585

In [16]:
sample_size = 10000
basket_sample = basket_list.sample(n=sample_size, random_state=42)

In [17]:
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(basket_sample['products']).transform(basket_sample['products'])
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = apriori(df_encoded, min_support=0.01, use_colnames=True)

In [18]:
df_encoded.head()

,0% Greek Strained Yogurt,1% Low Fat Milk,1% Lowfat Milk,100 Calorie Per Bag Popcorn,100% Apple Juice,100% Grated Parmesan Cheese,100% Lactose Free Fat Free Milk,100% Natural Spring Water,100% Pure Pumpkin,100% Raw Coconut Water,...,YoKids Squeeze! Organic Strawberry Flavor Yogurt,"YoKids Squeezers Organic Low-Fat Yogurt, Strawberry",YoKids Strawberry Banana/Strawberry Yogurt,Yobaby Organic Plain Yogurt,"Yogurt, Lowfat, Strawberry","Yogurt, Strained Low-Fat, Coconut",Yotoddler Organic Pear Spinach Mango Yogurt,Yukon Gold Potatoes 5lb Bag,ZBar Organic Chocolate Brownie Energy Snack,Zero Calorie Cola
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
# generate association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3)

print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10))

rules_sorted = rules.sort_values('lift', ascending=False)
print(rules_sorted[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10))

                              antecedents               consequents  support  \
0  (Organic Large Extra Fancy Fuji Apple)  (Bag of Organic Bananas)   0.0115
1                   (Organic Raspberries)  (Bag of Organic Bananas)   0.0216
2                        (Cucumber Kirby)                  (Banana)   0.0142
3                      (Honeycrisp Apple)                  (Banana)   0.0135
4                    (Organic Fuji Apple)                  (Banana)   0.0157
5                   (Seedless Red Grapes)                  (Banana)   0.0122
6                          (Strawberries)                  (Banana)   0.0230
7                         (Yellow Onions)                  (Banana)   0.0116

   confidence      lift
0    0.347432  2.069279
1    0.316716  1.886334
2    0.317673  1.507705
3    0.349741  1.659900
4    0.368545  1.749144
5    0.322751  1.531805
6    0.352761  1.674232
7    0.328612  1.559620
                              antecedents               consequents  support  \
0  (Organic Large Extra Fancy Fuji Apple)  (Bag of Organic Bananas)   0.0115
1                   (Organic Raspberries)  (Bag of Organic Bananas)   0.0216
4                    (Organic Fuji Apple)                  (Banana)   0.0157
6                          (Strawberries)                  (Banana)   0.0230
3                      (Honeycrisp Apple)                  (Banana)   0.0135
7                         (Yellow Onions)                  (Banana)   0.0116
5                   (Seedless Red Grapes)                  (Banana)   0.0122
2                        (Cucumber Kirby)                  (Banana)   0.0142

   confidence      lift
0    0.347432  2.069279
1    0.316716  1.886334
4    0.368545  1.749144
6    0.352761  1.674232
3    0.349741  1.659900
7    0.328612  1.559620
5    0.322751  1.531805
2    0.317673  1.507705

Support = frequency of the association
Confidence = % of times that when I buy antecedent I get consequent
Lift = Probability of association compared to random = PB(A)/P(B)

TEST ECLAT

In [8]:
from collections import defaultdict

# Convert dataset
transactions = {}
for idx, row in basket_list.iterrows():
    transactions[f"T{idx}"] = row['products']

min_support = int(0.005 * len(transactions))

# generate tidsets
def generate_tidsets(transactions):
    item_tidset = defaultdict(set)
    for tid, items in transactions.items():
        for item in items:
            item_tidset[item].add(tid)
    return item_tidset

def eclat(prefix, items, min_support, frequent_itemsets):
    while items:
        item, tidset = items.pop()
        support = len(tidset)
        if support >= min_support:
            new_itemset = prefix + [item]
            frequent_itemsets[frozenset(new_itemset)] = support
            suffix = []
            for other_item, other_tidset in items:
                intersection = tidset & other_tidset
                if len(intersection) >= min_support:
                    suffix.append((other_item, intersection))
            if suffix:
                eclat(new_itemset, suffix, min_support, frequent_itemsets)

item_tidset = generate_tidsets(transactions)
items = sorted(item_tidset.items(), key=lambda x: len(x[1]))
frequent_itemsets = {}
eclat([], items, min_support, frequent_itemsets)

In [15]:
for itemset, support in sorted(frequent_itemsets.items(), 
                                key=lambda x: (-len(x[0]), -x[1], sorted(list(x[0])))):
    print(list(itemset), "=>", support)

['Bag of Organic Bananas', 'Organic Hass Avocado'] => 53485
['Organic Strawberries', 'Bag of Organic Bananas'] => 52236
['Organic Strawberries', 'Banana'] => 48618
['Organic Avocado', 'Banana'] => 46487
['Banana', 'Organic Baby Spinach'] => 44109
['Bag of Organic Bananas', 'Organic Baby Spinach'] => 42457
['Strawberries', 'Banana'] => 35973
['Large Lemon', 'Banana'] => 34694
['Bag of Organic Bananas', 'Organic Raspberries'] => 34430
['Organic Strawberries', 'Organic Hass Avocado'] => 33984
['Organic Strawberries', 'Organic Baby Spinach'] => 31193
['Organic Fuji Apple', 'Banana'] => 29483
['Organic Hass Avocado', 'Organic Baby Spinach'] => 29027
['Organic Strawberries', 'Organic Raspberries'] => 28185
['Banana', 'Cucumber Kirby'] => 27755
['Banana', 'Organic Whole Milk'] => 27399
['Organic Hass Avocado', 'Banana'] => 27023
['Limes', 'Banana'] => 26468
['Organic Avocado', 'Organic Baby Spinach'] => 25980
['Banana', 'Honeycrisp Apple'] => 24550
['Bag of Organic Bananas', 'Organic Whole Milk'] => 22581
['Large Lemon', 'Limes'] => 22300
['Organic Hass Avocado', 'Organic Raspberries'] => 21268
['Seedless Red Grapes', 'Banana'] => 20915
['Large Lemon', 'Organic Avocado'] => 20421
['Organic Strawberries', 'Organic Avocado'] => 20207
['Organic Strawberries', 'Organic Whole Milk'] => 20190
['Bag of Organic Bananas', 'Organic Yellow Onion'] => 20113
['Bag of Organic Bananas', 'Apple Honeycrisp Organic'] => 20110
['Bag of Organic Bananas', 'Organic Large Extra Fancy Fuji Apple'] => 19846
['Organic Strawberries', 'Organic Blueberries'] => 19767
['Bag of Organic Bananas', 'Organic Avocado'] => 19718
['Organic Raspberries', 'Banana'] => 19404
['Bag of Organic Bananas', 'Organic Lemon'] => 18737
['Bag of Organic Bananas', 'Organic Zucchini'] => 18522
['Large Lemon', 'Organic Baby Spinach'] => 18478
['Limes', 'Organic Avocado'] => 18303
['Bag of Organic Bananas', 'Organic Blueberries'] => 18300
['Banana', 'Yellow Onions'] => 18149
['Organic Garlic', 'Organic Yellow Onion'] => 18042
['Organic Cucumber', 'Bag of Organic Bananas'] => 17766
['Organic Lemon', 'Organic Hass Avocado'] => 17662
['Banana'] => 375602
['Bag of Organic Bananas'] => 299905
['Organic Strawberries'] => 218515
['Organic Baby Spinach'] => 200529
['Organic Hass Avocado'] => 179588
['Organic Avocado'] => 149579
['Large Lemon'] => 126909
['Limes'] => 116680
['Organic Raspberries'] => 113698
['Organic Whole Milk'] => 111599
['Strawberries'] => 111031
['Organic Yellow Onion'] => 95737
['Organic Garlic'] => 92736
['Organic Zucchini'] => 88471
['Cucumber Kirby'] => 82691
['Organic Blueberries'] => 79728
['Organic Fuji Apple'] => 74149
['Organic Lemon'] => 73811
['Apple Honeycrisp Organic'] => 71882
['Organic Grape Tomatoes'] => 71240
['Organic Cucumber'] => 67693
['Honeycrisp Apple'] => 67113
['Seedless Red Grapes'] => 66358
['Organic Baby Carrots'] => 62999
['Organic Large Extra Fancy Fuji Apple'] => 62823
['Carrots'] => 62198
['Yellow Onions'] => 61968
['Organic Gala Apples'] => 61561
['Sparkling Water Grapefruit'] => 61172
['Organic Baby Arugula'] => 60727
['Fresh Cauliflower'] => 59687
['Original Hummus'] => 59591
['Organic Cilantro'] => 58333
['Organic Half & Half'] => 57344
['Michigan Organic Kale'] => 57194
['Organic Red Onion'] => 56815
['Organic Small Bunch Celery'] => 56651
['Asparagus'] => 55244
['Half & Half'] => 55202
['Organic Tomato Cluster'] => 54008
['Organic Blackberries'] => 50470
['Organic Italian Parsley Bunch'] => 50364
['Organic Whole String Cheese'] => 49962
['Organic Granny Smith Apple'] => 49226
['Organic Red Bell Pepper'] => 48819
['100% Whole Wheat Bread'] => 47406
['Red Peppers'] => 47228
['Green Bell Pepper'] => 47021
['Organic Unsweetened Almond Milk'] => 46936
['Organic Peeled Whole Baby Carrots'] => 46860
['Red Vine Tomato'] => 45854
['Blueberries'] => 44928
['Organic Ginger Root'] => 43445
['Organic Garnet Sweet Potato (Yam)'] => 43334
['Boneless Skinless Chicken Breasts'] => 42196
['Organic Kiwi'] => 41625
['Raspberries'] => 41564
['Small Hass Avocado'] => 40899
["Organic D'Anjou Pears"] => 40867
['Unsweetened Almondmilk'] => 39504
['Extra Virgin Olive Oil'] => 38976
['Organic Reduced Fat 2% Milk'] => 38449
['Bunched Cilantro'] => 38116
['Lime Sparkling Water'] => 37750
['Grated Parmesan'] => 37407
['Spring Water'] => 36975
['Organic Lacinato (Dinosaur) Kale'] => 36558
['Red Onion'] => 36059
['Jalapeno Peppers'] => 35795
['Organic Navel Orange'] => 35621
['Broccoli Crown'] => 35314
['Hass Avocados'] => 35120
['Organic Grade A Free Range Large Brown Eggs'] => 33553
['Large Alfresco Eggs'] => 33324
['Uncured Genoa Salami'] => 33130
['Orange Bell Pepper'] => 33020
['Roma Tomato'] => 32701
['Grape White/Green Seedless'] => 32578
['Organic Bartlett Pear'] => 31789
['Organic Broccoli'] => 31621
['Organic Black Beans'] => 31263
['Garlic'] => 30966
['Clementines, Bag'] => 30900
['Organic Carrot Bunch'] => 30265
['Shredded Parmesan'] => 30168
['Sparkling Natural Mineral Water'] => 30037
['Organic Romaine Lettuce'] => 29323
['Organic Reduced Fat Milk'] => 29189
['Bartlett Pears'] => 29142
['100% Raw Coconut Water'] => 28840
['Unsalted Butter'] => 28739
['Organic Sticks Low Moisture Part Skim Mozzarella String Cheese'] => 28143
['Granny Smith Apples'] => 27956
['Feta Cheese Crumbles'] => 27176
['Organic Russet Potato'] => 27067
['Unsweetened Original Almond Breeze Almond Milk'] => 26982
['Organic Broccoli Florets'] => 26825
['Organic Baby Broccoli'] => 26562
['Sparkling Lemon Water'] => 26559
['Organic Whole Strawberries'] => 26383
['Organic Large Brown Grade AA Cage Free Eggs'] => 26023
['Whipped Cream Cheese'] => 25612
['Total 2% with Strawberry Lowfat Greek Strained Yogurt'] => 25460
['Pure Irish Butter'] => 25299
['Frozen Organic Wild Blueberries'] => 25262
['Organic Spring Mix'] => 24936
['Organic Garbanzo Beans'] => 24881
['Organic Roma Tomato'] => 24878
['Sharp Cheddar Cheese'] => 24709
['Italian Sparkling Mineral Water'] => 24657
['Organic Extra Firm Tofu'] => 24334
['Green Beans'] => 24253
['Russet Potato'] => 23905
['Vanilla Almond Breeze Almond Milk'] => 23881
['Whole Milk'] => 23807
['No Salt Added Black Beans'] => 23594
['Organic Roasted Turkey Breast'] => 23405
['2% Reduced Fat Milk'] => 23068
['Pure Sparkling Water'] => 22974
['Organic Red Radish, Bunch'] => 22731
['Organic Coconut Milk'] => 22520
['100% Recycled Paper Towels'] => 22222
['Ground Turkey Breast'] => 22221
['Organic Milk'] => 22188
['Organic Sour Cream'] => 21951
['Organic Basil'] => 21864
['Total Greek Strained Yogurt'] => 21858
['Total 0% Nonfat Greek Yogurt'] => 21851
['Red Raspberries'] => 21789
['Shredded Mild Cheddar Cheese'] => 21592
['Yellow Bell Pepper'] => 21551
['Green Onions'] => 21521
['Organic Large Grade AA Brown Eggs'] => 21028
['Total 0% Greek Yogurt'] => 20991
['Organic Fat Free Milk'] => 20978
['Honey Nut Cheerios'] => 20779
['Fat Free Milk'] => 20314
['Pineapple Chunks'] => 20103
['Organic White Onions'] => 20070
['Fresh Ginger Root'] => 20055
['Unsweetened Vanilla Almond Milk'] => 20037
['Organic Hothouse Cucumbers'] => 20017
['Lightly Salted Baked Snap Pea Crisps'] => 19975
['Organic Heavy Whipping Cream'] => 19900
['Organic Celery Hearts'] => 19748
['Watermelon Chunks'] => 19730
['Romaine Hearts'] => 19703
['Organic Romaine'] => 19665
['Organic Bell Pepper'] => 19596
['Cantaloupe'] => 19379
['Total 2% All Natural Greek Strained Yogurt with Honey'] => 19175
['Baby Spinach'] => 18974
['Organic Bread with 21 Whole Grains'] => 18859
['Gala Apples'] => 18850
['Original Orange Juice'] => 18463
['Shredded Mozzarella'] => 18342
['Organic Spring Mix Salad'] => 18182
['Boneless Skinless Chicken Breast'] => 18135
['Organic Yellow Peaches'] => 18060
['Clementines'] => 17913
['Organic Green Seedless Grapes'] => 17912
['Brussels Sprouts'] => 17867
['Organic Green Cabbage'] => 17865
['Organic Bosc Pear'] => 17858
['Large Grapefruit'] => 17786
['Total 2% Lowfat Greek Strained Yogurt With Blueberry'] => 17724

In [9]:
# Convert in dataframe for mlxtend
eclat_df = pd.DataFrame([
    {'itemsets': itemset, 'support': support / len(transactions)} 
    for itemset, support in frequent_itemsets.items()
])
eclat_df.head()

                                            itemsets   support
0                                           (Banana)  0.263650
1                     (Organic Strawberries, Banana)  0.045601
2  (Organic Strawberries, Organic Baby Spinach, B...  0.008375
3  (Organic Strawberries, Organic Hass Avocado, B...  0.006104
4    (Organic Strawberries, Banana, Organic Avocado)  0.007735

In [ ]:
# Generate association rules
from mlxtend.frequent_patterns import association_rules

rules = association_rules(eclat_df, metric="confidence", min_threshold=0.3)

# Order by lift
rules_sorted = rules.sort_values('lift', ascending=False)

def extract_names(frozenset_items):
    return ', '.join(sorted(frozenset_items))

rules_sorted['antecedent'] = rules_sorted['antecedents'].apply(extract_names)
rules_sorted['consequent'] = rules_sorted['consequents'].apply(extract_names)

# Export without frozenset columns
rules_clean = rules_sorted[[
    'antecedent',
    'consequent', 
    'support',
    'confidence',
    'lift'
]]

rules_clean.to_csv('../data/processed/rules_clean.csv', index=False)

print(f"✅ {len(rules_clean)} règles exportées dans rules_clean.csv")
print(rules_clean.head(10))

✅ 95 règles exportées dans rules_clean.csv
                                           antecedent  \
94   Total 2% Lowfat Greek Strained Yogurt with Peach
93  Total 2% Lowfat Greek Strained Yogurt With Blu...
90  Total 2% Lowfat Greek Strained Yogurt With Blu...
89  Total 2% with Strawberry Lowfat Greek Strained...
91  Total 2% with Strawberry Lowfat Greek Strained...
92   Total 2% Lowfat Greek Strained Yogurt with Peach
88                              Sparkling Lemon Water
87                              Sparkling Lemon Water
86                               Lime Sparkling Water
84                                   Bunched Cilantro

                                           consequent   support  confidence  \
94  Total 2% Lowfat Greek Strained Yogurt With Blu...  0.005188    0.358039
93   Total 2% Lowfat Greek Strained Yogurt with Peach  0.005188    0.342580
90  Total 2% with Strawberry Lowfat Greek Strained...  0.007658    0.505699
89  Total 2% Lowfat Greek Strained Yogurt With Blu...  0.007658    0.357079
91   Total 2% Lowfat Greek Strained Yogurt with Peach  0.006525    0.304237
92  Total 2% with Strawberry Lowfat Greek Strained...  0.006525    0.450306
88                               Lime Sparkling Water  0.006138    0.312692
87                         Sparkling Water Grapefruit  0.006619    0.337210
86                         Sparkling Water Grapefruit  0.009469    0.327542
84                                              Limes  0.010332    0.330201

         lift
94  23.641803
93  23.641803
90  23.578432
89  23.578432
91  20.995710
92  20.995710
88  10.815849
87   7.298054
86   7.088808
84   3.211211

In [14]:

# Charge ton CSV de règles
rules = pd.read_csv('../data/processed/rules_clean.csv')

# Extrait TOUS les produits uniques (antécédents + conséquents)
all_products = set()

for _, row in rules.iterrows():
    # Ajoute produits des antécédents
    all_products.update(row['antecedent'].split(', '))
    # Ajoute produits des conséquents
    all_products.update(row['consequent'].split(', '))

# Crée DataFrame
products_list = pd.DataFrame({
    'product_name': sorted(all_products)
})

# Export
products_list.to_csv('../data/processed/products_in_rules.csv', index=False)

print(f"✅ {len(products_list)} produits uniques exportés")
print(products_list.head(10))

✅ 74 produits uniques exportés
                        product_name
0             100% Raw Coconut Water
1             100% Whole Wheat Bread
2           Apple Honeycrisp Organic
3                                Bag
4             Bag of Organic Bananas
5                             Banana
6                     Bartlett Pears
7                        Blueberries
8  Boneless Skinless Chicken Breasts
9                     Broccoli Crown